name: Deploy Webapp

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Deploy Webapp
        run: |
          python .github/workflows/deploy_webapp.py \
            --host "${{ vars.PA_HOST }}" \
            --username "${{ secrets.PA_USERNAME }}" \
            --password "${{ secrets.PA_PASSWORD }}" \
            --token "${{ secrets.PA_TOKEN }}" \
            --console-id "${{ vars.PA_CONSOLE_ID }}"