name: Deploy Webapp

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull PythonAnywhere
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.PA_TOKEN }}" \
            -d "input=git pull" \
            "${{ vars.PA_HOST }}/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/${{ vars.PA_CONSOLE_ID }}/send_input/"
      
      - name: Reload webapp
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.PA_TOKEN }}" \
            "${{ vars.PA_HOST }}/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ vars.PA_DOMAIN_NAME }}/reload/"
